from fastapi import HTTPException
from pydantic import BaseModel
from typing import Dict, List, Any, Optional
import logging
import json
import os
from dotenv import load_dotenv
import copy
import uuid
import google.generativeai as genai

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Load environment variables
load_dotenv()

# --- AI Builder Globals --- 
# Store for AI Builder chat conversations
builder_sessions: Dict[str, Dict[str, Any]] = {}
# Global instance for the AI Builder Gemini client
ai_builder_model = None

# --- API Models ---
class BuilderChatInput(BaseModel):
    message: str
    session_id: str # Use a unique ID for each builder session (e.g., generated by frontend)

class BuilderChatResponse(BaseModel):
    response: str
    state: Optional[Dict[str, Any]] = None

# --- AI Builder Core Functions ---
def initialize_ai_builder_model():
    """Initialize the dedicated AI Builder model on startup."""
    global ai_builder_model
    api_key = os.getenv("AI_CHATBOT_BUILDER_API")
    if not api_key:
        logger.error("AI_CHATBOT_BUILDER_API key not found in environment variables. Builder disabled.")
        return
    try:
        logger.info("Initializing AI Builder Gemini model (gemini-1.5-flash)")
        # Use a separate configuration for the builder if possible, or ensure the global one is set
        genai.configure(api_key=api_key)
        # Simple config for the builder bot
        generation_config = {"temperature": 0.6, "max_output_tokens": 1000}
        ai_builder_model = genai.GenerativeModel(
            model_name='gemini-1.5-flash',
            generation_config=generation_config
        )
        logger.info("AI Builder model initialized successfully.")
    except Exception as e:
        logger.error(f"Failed to initialize AI Builder model: {str(e)}")
        ai_builder_model = None # Ensure it's None if init fails

async def generate_builder_response(session_id: str, user_message: str) -> Dict[str, Any]:
    """Handles the conversation logic with the AI Builder."""
    global builder_sessions, ai_builder_model

    if not ai_builder_model:
        logger.warning("AI Builder model not initialized, cannot process chat.")
        return {"response": "Sorry, the AI builder is currently unavailable.", "state": None}

    # Get or create session state
    if session_id not in builder_sessions:
        logger.info(f"Creating new AI builder session: {session_id}")
        builder_sessions[session_id] = {
            "history": [],
            "step": "start",
            "workflow_data": {},
            "user_provided_prompt": None # To store the original prompt
        }
    
    session_state = builder_sessions[session_id]
    history = session_state["history"]
    step = session_state["step"]
    workflow_data = session_state["workflow_data"]
    user_provided_prompt = session_state.get("user_provided_prompt") # Get original prompt if exists

    # Add user message to history (for context)
    # Use a format compatible with Gemini API history
    history.append({"role": "user", "parts": [user_message]})

    ai_response_text = "An internal error occurred."
    next_step = step # Default to staying on the same step
    ready_to_create = False
    updated_workflow_data = copy.deepcopy(workflow_data) # Work on a copy

    try:
        logger.info(f"AI Builder - Session: {session_id}, Current Step: {step}, User Message: {user_message[:50]}...")
        # Start a chat session using the history
        chat = ai_builder_model.start_chat(history=history[:-1]) # Use history BEFORE the current user message
        
        # --- NEW Conversation Logic --- 
        if step == "start":
            # Ask what kind of workflow
            system_instruction = "You are SentientX AI Workflow Builder. Greet the user and ask what kind of workflow they want to build. Only AI Agent Chatbot workflows are supported currently."
            response = await chat.send_message_async(f"{system_instruction} User message: '{user_message}'")
            ai_response_text = response.text
            # Check if user response indicates chatbot
            if "chatbot" in user_message.lower() or "agent" in user_message.lower():
                # User wants chatbot, ask for type/purpose next
                system_instruction_next = "Great! What specific type of AI Agent Chatbot would you like to build? (e.g., sales assistant, customer support bot, appointment scheduler)"
                response_next = await chat.send_message_async(system_instruction_next)
                ai_response_text = response_next.text
                next_step = "get_chatbot_type"
            elif user_message.lower() == 'start': # Handle initial call from frontend
                 # Just return the initial greeting/question
                 pass # ai_response_text already set
                 next_step = "start"
            else:
                # User wants something else, AI should handle saying only chatbots are supported
                # The initial response likely already covers this based on the system instruction
                next_step = "start"
                 
        elif step == "get_chatbot_type":
            # User described the type of chatbot
            chatbot_type_description = user_message.strip()
            updated_workflow_data['chatbot_type_description'] = chatbot_type_description
            # Now ask for the system prompt
            system_instruction = f"Okay, you want to build a '{chatbot_type_description}'. Now, please provide the **System Prompt** you want this chatbot to use. This tells the AI its role, personality, and instructions."
            response = await chat.send_message_async(system_instruction) 
            ai_response_text = response.text
            next_step = "receive_system_prompt"

        elif step == "receive_system_prompt":
            # User has provided the system prompt
            received_prompt = user_message.strip()
            if len(received_prompt) < 10: # Basic check for actual prompt content
                system_instruction = "That doesn't seem like a full system prompt. Please provide the detailed instructions for your chatbot."
                response = await chat.send_message_async(system_instruction)
                ai_response_text = response.text
                next_step = "receive_system_prompt" # Stay here
            else:
                session_state["user_provided_prompt"] = received_prompt # Store original
                updated_workflow_data['system_prompt'] = received_prompt # Store tentatively
                # Use triple quotes for the multi-line f-string
                system_instruction = f"""Got it. Here is the system prompt you provided:

```
{received_prompt}
```

Would you like me to try and improve or refine this prompt for you? (yes/no)"""
                response = await chat.send_message_async(system_instruction)
                ai_response_text = response.text
                next_step = "offer_refinement_decision"

        elif step == "offer_refinement_decision":
            # Ask the AI to decide based on user response to refinement offer
            system_instruction = f"User was asked if they want help improving the prompt. Their response was '{user_message}'. If 'yes', acknowledge and proceed to refine. If 'no', confirm saving the original prompt and move to model confirmation. Otherwise, ask for 'yes' or 'no'."
            response = await chat.send_message_async(system_instruction)
            ai_response_text = response.text
            if user_message.lower().strip() == 'yes':
                next_step = "refine_prompt"
            elif user_message.lower().strip() == 'no':
                updated_workflow_data['system_prompt'] = user_provided_prompt # Ensure original is saved
                next_step = "confirm_model" # Skip refinement
            else:
                next_step = "offer_refinement_decision" # Ask again

        elif step == "refine_prompt":
            # This step generates the refined prompt and asks for confirmation
            if not user_provided_prompt:
                 ai_response_text = "Error: Cannot refine without the original prompt. Let's go back. Please provide the system prompt."
                 next_step = "receive_system_prompt"
            else:
                system_instruction_for_refinement = f"Improve this system prompt for an AI Agent Chatbot, making it clear, concise, and effective: ```{user_provided_prompt}```. Output ONLY the improved prompt text."
                refinement_response = await ai_builder_model.generate_content_async(system_instruction_for_refinement)
                refined_prompt = refinement_response.text.strip()
                updated_workflow_data['system_prompt_refined'] = refined_prompt 
                
                # Use triple quotes for the multi-line f-string
                system_instruction_for_confirmation = f"""Here is a suggested refinement:

```
{refined_prompt}
```

Would you like to use this improved version? (yes/no)"""
                response = await chat.send_message_async(system_instruction_for_confirmation)
                ai_response_text = response.text
                next_step = "confirm_refined_prompt"

        elif step == "confirm_refined_prompt":
            # Ask AI to decide based on user response to the *refined* prompt offer
            refined_prompt = updated_workflow_data.get('system_prompt_refined')
            system_instruction = f"User was shown the refined prompt: ```{refined_prompt}```. Their response was '{user_message}'. If 'yes', confirm saving refined prompt and move to model confirmation. If 'no', ask if they want to use their *original* prompt instead (yes/no). Otherwise, ask for 'yes' or 'no' regarding the refined prompt."
            response = await chat.send_message_async(system_instruction)
            ai_response_text = response.text
            
            if user_message.lower().strip() == 'yes':
                updated_workflow_data['system_prompt'] = refined_prompt # Save refined version
                next_step = "confirm_model"
            elif user_message.lower().strip() == 'no':
                next_step = "confirm_original_after_refine" # Ask about original
            else:
                next_step = "confirm_refined_prompt" # Ask again about refined

        elif step == "confirm_original_after_refine":
            # Ask AI to decide based on user response about using original after rejecting refined
            system_instruction = f"User rejected the refined prompt. They were asked if they want to use their original prompt: ```{user_provided_prompt}```. Their response was '{user_message}'. If 'yes', confirm saving original and move to model confirmation. If 'no', ask them to provide a new prompt. Otherwise, ask for 'yes' or 'no' regarding the original prompt."
            response = await chat.send_message_async(system_instruction)
            ai_response_text = response.text
            if user_message.lower().strip() == 'yes':
                updated_workflow_data['system_prompt'] = user_provided_prompt # Save original
                next_step = "confirm_model"
            elif user_message.lower().strip() == 'no':
                 # Clear stored prompts and go back
                 session_state["user_provided_prompt"] = None
                 updated_workflow_data.pop('system_prompt', None)
                 updated_workflow_data.pop('system_prompt_refined', None)
                 next_step = "receive_system_prompt"
            else:
                 next_step = "confirm_original_after_refine" # Ask again

        # --- Steps after prompt confirmation (confirm_model onwards) --- 
        elif step == "confirm_model":
             # System instruction already included asking about the model in previous steps
             system_instruction = "User is confirming the model. Remind them only Gemini 1.5 Flash is available. If they say 'yes', proceed to ask for API Key ID. If they say anything else, reiterate the limitation and ask for 'yes'."
             response = await chat.send_message_async(f"{system_instruction} User response: '{user_message}'") 
             ai_response_text = response.text
             if user_message.lower().strip() == 'yes':
                 updated_workflow_data['model'] = 'gemini-1.5-flash'
                 updated_workflow_data['provider'] = 'gemini' 
                 next_step = "get_api_key"
             else:
                 next_step = "confirm_model"

        elif step == "get_api_key":
             system_instruction = "User confirmed model. Ask for the API Key ID (found in Credentials)."
             # Pass previous AI response for context, AI asks the question
             response = await chat.send_message_async(f"{system_instruction} Previous AI message was: {history[-2]['parts'][0]}. User input (API Key ID): '{user_message}'") 
             ai_response_text = response.text
             api_key_id = user_message.strip()
             is_potentially_valid = len(api_key_id) > 10 and not any(c in api_key_id for c in ' <>[]{}\"')
             if is_potentially_valid:
                 updated_workflow_data['apiKeyId'] = api_key_id
                 # AI response should now ask for workflow name
                 next_step = "get_name"
             else: # Keep asking if invalid
                 # AI response should indicate invalid and ask again
                 next_step = "get_api_key"

        elif step == "get_name":
             system_instruction = "User provided API Key ID. Ask for the workflow name."
             response = await chat.send_message_async(f"{system_instruction} User input (Workflow Name): '{user_message}'")
             ai_response_text = response.text
             if len(user_message.strip()) > 0:
                  updated_workflow_data['name'] = user_message.strip()
                  # AI response should ask for description
                  next_step = "get_wf_description"
             else:
                  # AI response should ask for name again
                  next_step = "get_name"

        elif step == "get_wf_description":
             system_instruction = "User provided name. Ask for the workflow description."
             response = await chat.send_message_async(f"{system_instruction} User input (Description): '{user_message}'")
             ai_response_text = response.text
             updated_workflow_data['description'] = user_message.strip()
             # AI response should ask for tags
             next_step = "get_tags"

        elif step == "get_tags":
             tags = [tag.strip() for tag in user_message.split(',') if tag.strip()]
             updated_workflow_data['tags'] = tags
             # AI presents summary and asks for confirmation
             system_instruction = f"User provided tags: {tags}. Present a summary (Name, Desc, Tags, Model, API ID, Prompt) and ask if ready to create."
             summary_text = f"Name: {updated_workflow_data.get('name', 'N/A')}, Desc: {updated_workflow_data.get('description', 'N/A')}, Tags: {tags or 'None'}, Model: {updated_workflow_data.get('model', 'N/A')}, API Key ID: {updated_workflow_data.get('apiKeyId', 'N/A')}, Prompt: {updated_workflow_data.get('system_prompt', 'N/A')[:40]}..."
             response = await chat.send_message_async(f"{system_instruction} Summary: {summary_text}")
             ai_response_text = response.text
             next_step = "summarize"

        elif step == "summarize":
             # AI confirms readiness based on user input
             system_instruction = "User shown summary. If 'yes', confirm ready and tell them to use button. If not, ask what to change."
             response = await chat.send_message_async(f"{system_instruction} User response: '{user_message}'")
             ai_response_text = response.text
             if user_message.lower().strip() == 'yes':
                 ready_to_create = True
                 next_step = "ready_to_create"
             else:
                 # AI should ask what to change
                 next_step = "summarize" # Stay here for now
                 
        elif step == "ready_to_create":
             # AI reminds user to click the button
             system_instruction = "User is ready. Remind them to use the 'Create Workflow from Chat' button."
             response = await chat.send_message_async(system_instruction)
             ai_response_text = response.text
             ready_to_create = True
             next_step = "ready_to_create"

        else:
            # Fallback
            logger.warning(f"AI Builder reached unknown step: {step}")
            response = await chat.send_message_async("I seem to have lost my place. Let's restart. What kind of workflow do you want to build? Remember, only AI Agent Chatbots are supported now.")
            ai_response_text = response.text
            next_step = "start"
            updated_workflow_data = {}
            session_state["user_provided_prompt"] = None
            builder_sessions[session_id]["history"] = [] 

    except Exception as e:
        logger.error(f"Error during AI Builder chat processing (step: {step}): {str(e)}", exc_info=True)
        ai_response_text = "Sorry, I encountered an error processing your request. Please try again."

    # Add AI response to history for future context
    history.append({"role": "model", "parts": [ai_response_text]})

    # Update session state
    session_state["step"] = next_step
    session_state["workflow_data"] = updated_workflow_data
    session_state["history"] = history[-20:] # Keep last 10 pairs (actually 20 entries = 10 pairs)

    logger.info(f"AI Builder - Session: {session_id}, Next Step: {next_step}, Ready: {ready_to_create}")

    return {
        "response": ai_response_text,
        "state": {
            "step": next_step,
            "ready_to_create": ready_to_create,
            "workflow_data": updated_workflow_data if ready_to_create else None 
        }
    } 