import { TriggerNode } from "./nodes/TriggerNode";
import { ActionNode } from "./nodes/ActionNode";
import { OutputNode } from "./nodes/OutputNode";
import { 
  Zap, 
  Globe, 
  FileJson, 
  BrainCircuit, 
  Database, 
  Mail, 
  MessageSquare,
  CircleIcon,
  SquareIcon,
  Bot,
  AlertTriangle,
  MessageCircle,
  MemoryStickIcon,
  DatabaseZap,
  Webhook,
  Wrench
} from "lucide-react";

// Registry of node types mapped to their respective components
export const nodeTypes = {
  trigger: TriggerNode,
  action: ActionNode,
  output: OutputNode,
};

// Catalog of available nodes for the NodePanel
export const nodeCatalog = [
 
  {
    type: 'action',
    label: 'HTTP Request',
    description: 'Make an HTTP request',
    icon: Globe,
    category: 'Actions',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Transform Data',
    description: 'Transform data using JavaScript',
    icon: FileJson,
    category: 'Actions',
    hidden: true,
  },
  {
    type: 'action',
    label: 'OpenAI API',
    description: 'OpenAI Chat Model',
    icon: BrainCircuit,
    category: 'LLM APIs',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Google Gemini API',
    description: 'Gemini Set of Model',
    icon: BrainCircuit,
    category: 'LLM APIs',
    hidden: false,
  },
  {
    type: 'action',
    label: 'Anthropic API',
    description: 'Claude Set Of Model',
    icon: BrainCircuit,
    category: 'LLM APIs',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Deepseek API',
    description: 'Deepseek Set Of Model',
    icon: BrainCircuit,
    category: 'LLM APIs',
    hidden: true,
  },
  // {
  //   type: 'action',
  //   label: 'Database Query',
  //   description: 'Query a database',
  //   icon: Database,
  //   category: 'Actions',
  // },
  {
    type: 'action',
    label: 'Chat Trigger',
    description: 'Trigger the chat',
    icon: MessageCircle,
    category: 'Triggers',
    hidden: false,
  },
  {
    type: 'action',
    label: 'AI Agent',
    description: 'AI-Powered Automation',
    icon: Bot,
    category: 'AI',
    childNodes: [
      { label: 'LLM', type: 'connection' },
      { label: 'Memory', type: 'connection' },
      { label: 'Tool', type: 'connection' },
      { label: 'Parser', type: 'connection' }
    ],
    hidden: true,
  },
  {
    type: 'action',
    label: 'Supabase AI Agent',
    description: 'interact with supabase with natural language',
    icon: Bot,
    category: 'Pre-Built Agents',
    hidden: false,
  },
  {
    type: 'action',
    label: 'Multi Agent (BaseAgent)',
    description: 'BaseAgent instances - Multi-Agent System (MAS)',
    icon: Bot,
    category: 'Multi Agentic',
    hidden: false,
  },
  {
    type: 'action',
    label: 'LLM Agent',
    description: 'acting as the "thinking" part of your application',
    icon: Bot,
    category: 'Multi Agentic',
    hidden: false,
  },
  {
    type: 'action',
    label: 'Sequential agent',
    description: 'executes its sub-agents in the order they are specified in the list',
    icon: Bot,
    category: 'Multi Agentic',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Loop agent',
    description: 'executes its sub-agents in a loop (i.e. iteratively)',
    icon: Bot,
    category: 'Multi Agentic',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Parallel agent',
    description: 'executes all sub-agents in parallel',
    icon: Bot,
    category: 'Multi Agentic',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Redis Memory',
    description: 'Stores a customizable length of chat history',
    icon: DatabaseZap,
    category: 'AI',
    hidden: true,
  },
  {
    type: 'action',
    label: 'Respond to Webhook',
    description: 'Works similar to API Server',
    icon: Webhook,
    category: 'Webhook',
    hidden: false,
  },
  {
    type: 'action',
    label: 'Webhook',
    description: 'Start the workflow when a webhook is called',
    icon: Webhook,
    category: 'Webhook',
    hidden: true,
  },
  {
    type: 'action',
    label: 'get_price',
    description: 'Return the latest stock price for a ticker symbol.',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'YahooFinanceNewsTool',
    description: 'Return recent finance headlines from Yahoo Finance.',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'BraveSearchTool',
    description: 'Search the web using the Brave API.',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'ScrapeWebsiteTool',
    description: 'Scrape a website',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'EXASearchTool',
    description: 'perform a semantic search for a specified query',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'hyperbrowser_tool',
    description: 'Use the hyperbrowser tool to perform browser automation tasks.',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  },
  {
    type: 'action',
    label: 'Serper API',
    description: 'serper tool to perform search queries on the internet.',
    icon: Wrench,
    category: 'Tools',
    hidden: false,
  }
]; 